version: '3'

services:
  app-keycloak:
    image: quay.io/keycloak/keycloak:15.1.1
    container_name: keycloack
    environment:
      KEYCLOAK_USER: admin_user
      KEYCLOAK_PASSWORD: admin_password
      DB_VENDOR: mysql
      DB_ADDR: db-mysql-kc
      DB_PORT: 3306
      DB_USER: keycloak_user
      DB_PASSWORD: keycloak_password
      DB_DATABASE: keycloak_db
    ports:
      - 8181:8080
    depends_on:
      - db-mysql-kc
    networks:
      - keycloak-and-mysql-network  
  db-mysql-kc:
    image: mysql:8.0.27
    container_name: keycloack_mysql
    restart: always
    tty: true
    ports:
      - 3366:3306
    environment:
      MYSQL_USER: keycloak_user
      MYSQL_PASSWORD: keycloak_password
      MYSQL_DATABASE: keycloak_db
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - keycloak-and-mysql-volume:/var/lib/mysql
    networks:
      - keycloak-and-mysql-network

networks:
  keycloak-and-mysql-network:

volumes:
  keycloak-and-mysql-volume: