version: '3'

services:
  app:
    build: .
    container_name: keycloack
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_ADDR=db
      - DB_VENDOR=mysql
      - DB_DATABASE=keycloak
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
    ports:
      - 8083:8080
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: keycloack_mysql
    restart: always
    tty: true
    ports:
      - 33060:3306
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=keycloack
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root          